[cerebrium.deployment]
name = "marker-service"
python_version = "3.11"
disable_auth = true
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*', 'scripts/*']

[cerebrium.runtime.custom]
dockerfile_path = "./Dockerfile"  
port = 8192
healthcheck_endpoint = "/health"
readycheck_endpoint = "/ready"
entrypoint = ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8192"]

[cerebrium.hardware]
cpu = 8
memory = 32.0
gpu_count = 1
compute = "AMPERE_A10"
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 1
cooldown = 600
response_grace_period = 3600
replica_concurrency = 1
scaling_metric = "concurrency_utilization"
scaling_target = 70
scaling_buffer = 0